// utils/sanitize.ts — HGRAND OS
//
// Document content in this app is not trustworthy: it is generated by the AI,
// imported from files, or typed by the coach. It then gets interpolated into
// HTML strings that are rendered inside a WebView (document-viewer) and into
// print-to-PDF templates. Both are execution contexts, so anything user- or
// model-supplied has to be neutralised on the way in.

/**
 * Escape the five characters that can break out of an HTML text node or
 * attribute value. Use this for any single value dropped into a template.
 */
export function escapeHtml(value: unknown): string {
  if (value == null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Validate a URI destined for an <img src>. Only data: images and https: are
 * allowed; `javascript:` and friends are dropped entirely.
 */
export function safeImageUri(uri: unknown): string {
  if (typeof uri !== 'string') return '';
  const trimmed = uri.trim();
  const isDataImage = /^data:image\/(png|jpe?g|gif|webp|svg\+xml);base64,[A-Za-z0-9+/=\s]+$/i.test(trimmed);
  const isHttps = /^https:\/\//i.test(trimmed);
  const isLocalFile = /^file:\/\//i.test(trimmed);
  if (!isDataImage && !isHttps && !isLocalFile) return '';
  return escapeHtml(trimmed);
}

/**
 * Strip active content from a block of HTML that we intend to render as-is.
 *
 * This is a denylist, which is weaker than a real parser-based sanitizer — it
 * is paired with a restrictive CSP at the render site so that anything slipping
 * through still cannot execute or phone home. If rich documents ever become
 * user-shareable rather than coach-private, replace this with DOMPurify.
 */
export function sanitizeDocumentHtml(html: unknown): string {
  if (typeof html !== 'string') return '';
  return (
    html
      // Whole elements that can execute or embed remote content.
      .replace(/<\s*(script|iframe|object|embed|link|meta|base|form|svg)\b[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
      .replace(/<\s*(script|iframe|object|embed|link|meta|base|form|svg)\b[^>]*\/?>/gi, '')
      // Inline event handlers: onclick=, onerror=, onload=...
      .replace(/\son\w+\s*=\s*"[^"]*"/gi, '')
      .replace(/\son\w+\s*=\s*'[^']*'/gi, '')
      .replace(/\son\w+\s*=\s*[^\s>]+/gi, '')
      // Pseudo-protocols in href/src/action attributes.
      .replace(/(href|src|action|formaction)\s*=\s*"\s*(javascript|vbscript|data:text\/html)[^"]*"/gi, '$1="#"')
      .replace(/(href|src|action|formaction)\s*=\s*'\s*(javascript|vbscript|data:text\/html)[^']*'/gi, "$1='#'")
      // CSS expression()/url(javascript:) tricks.
      .replace(/expression\s*\(/gi, '')
      .replace(/url\s*\(\s*['"]?\s*javascript:/gi, 'url(')
  );
}
